<?php echo '<?xml'; ?> version='1.0' encoding='UTF-8' ?>
<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">
    <channel>
        <title>{store_name} Products</title>
        <link>{store_url}</link>
        <description>Promotions feed. Generated by WooCommerce Google Product Feed Plugin
            v{version}. (https://plugins.leewillis.co.uk/downloads/woocommerce-google-product-feed/). Feed URL:
            {feed_url}}
        </description>
